server:
  port: 8083
spring:
  config:
    import: classpath:/application.yml
    activate:
      on-profile: dev

  datasource:
    url: ${SYNC_DB_URL:jdbc:mysql://localhost:3306/synq?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&createDatabaseIfNotExist=true}
    username: ${SYNC_DB_USER:root}
    password: ${SYNC_DB_PASSWORD:root}

  flyway:
    url: ${SYNC_DB_URL:jdbc:mysql://localhost:3306/synq?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&createDatabaseIfNotExist=true}
    user: ${SYNC_DB_USER:root}
    password: ${SYNC_DB_PASSWORD:root}

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:9003/realms/synq}

  data:
    redis:
      host: ${REDIS_HOST:localhost}
